index:
    path: /
    controller: App\Controller\TestController::index

login:
    path: /login
    controller: App\Controller\SecurityController::login

register:
    path: /register
    controller: App\Controller\RegistrationController::register